FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_VIDUCATE_BASE_URL=http://localhost:8000/api/v1
ENV VITE_VIDUCATE_BASE_URL=${VITE_VIDUCATE_BASE_URL}

EXPOSE 5173

CMD ["npm","run","dev","--","--host","0.0.0.0"]