export const STORAGE_KEYS = {
  token: "token",
  user: "user",
  forgetEmail: "forget_email",
  title: "video_title",
  description: "video_description",
  videoURL: "video_url",
  selectType: "select_type",
  currentTime: "lms_current_time",
  selectedTopic: "lms_selected_topic",
  marks: "marks",
  video_Id: "video_id",
  flashcardSession: "flashcards-session",
  topics: "video_topics",
  chatSessions: "chat_sessions",
  completedTopics: "complete_topics",
  mind_map_state: "mindmap-ui-state",
};
