"""add reset_token fields to user

Revision ID: 35d278af6e63
Revises: b9f5d662a2b2
Create Date: 2026-03-02 22:33:43.902252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d278af6e63'
down_revision: Union[str, Sequence[str], None] = 'b9f5d662a2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_token_expires')
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
