"""add locked_until to user

Revision ID: 4ac1d8899c9d
Revises: r1s2t3u4v5w6
Create Date: 2026-06-24 14:10:29.274954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac1d8899c9d'
down_revision: Union[str, Sequence[str], None] = 'r1s2t3u4v5w6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_question', sa.Column('concept', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_user_quiz_results_quiz_id'), table_name='user_quiz_results')
    op.drop_index(op.f('ix_user_quiz_results_user_id'), table_name='user_quiz_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_quiz_results_user_id'), 'user_quiz_results', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_quiz_results_quiz_id'), 'user_quiz_results', ['quiz_id'], unique=False)
    op.drop_column('user', 'locked_until')
    op.drop_column('quiz_question', 'concept')
    # ### end Alembic commands ###
