"""add  chat session and messages tables

Revision ID: 575a7230b66c
Revises: b3c4d5e6f7a8
Create Date: 2026-05-07 16:49:02.696603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575a7230b66c'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('current_time', sa.Integer(), nullable=True),
    sa.Column('question_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('answer_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.drop_index(op.f('ix_quiz_question_segment_id'), table_name='quiz_question')
    op.execute(
        "ALTER TABLE segment_summary ALTER COLUMN content TYPE JSON USING content::json"
    )

    op.execute(
        "ALTER TABLE video_summary ALTER COLUMN content TYPE JSON USING content::json"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_summary', 'content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('segment_summary', 'content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_quiz_question_segment_id'), 'quiz_question', ['segment_id'], unique=False)
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
