"""add summary_tables to video

Revision ID: 73c67c2abc53
Revises: 8572bda6f6b5
Create Date: 2026-04-19 12:01:17.216361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c67c2abc53'
down_revision: Union[str, Sequence[str], None] = '8572bda6f6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_summary',
    sa.Column('sum_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sum_id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('segment_summary',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_summary')
    op.drop_table('video_summary')
    # ### end Alembic commands ###
