"""add concept column

Revision ID: 81b32ab0e762
Revises: c22211313a42
Create Date: 2026-06-17 15:18:54.465432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b32ab0e762'
down_revision: Union[str, Sequence[str], None] = 'c22211313a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_question', sa.Column('concept', sa.String(length=255), nullable=True))
    op.add_column('user_quiz_results', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('user_quiz_results', sa.Column('trials', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_quiz_user', 'user_quiz_results', ['quiz_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quiz_user', 'user_quiz_results', type_='unique')
    op.drop_column('user_quiz_results', 'trials')
    op.drop_column('user_quiz_results', 'score')
    op.drop_column('quiz_question', 'concept')
    # ### end Alembic commands ###
