"""add content_hash to video

Revision ID: 8572bda6f6b5
Revises: 9e7d38ac822f
Create Date: 2026-04-14 18:09:10.099668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8572bda6f6b5'
down_revision: Union[str, Sequence[str], None] = '9e7d38ac822f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_video_content_hash'), 'video', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_content_hash'), table_name='video')
    op.drop_column('video', 'content_hash')
    # ### end Alembic commands ###
