"""init

Revision ID: 893bfeaa6773
Revises: 
Create Date: 2026-06-26 21:51:45.327016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893bfeaa6773'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('study_field', sa.String(length=100), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('settings',
    sa.Column('sett_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sett_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('video',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=True),
    sa.Column('current_time', sa.Integer(), nullable=True),
    sa.Column('last_watched_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('bookmarks', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vid')
    )
    op.create_index(op.f('ix_video_content_hash'), 'video', ['content_hash'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('content_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('summary_language', sa.String(length=10), nullable=True),
    sa.Column('quiz_language', sa.String(length=10), nullable=True),
    sa.Column('flashcard_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('mindmap',
    sa.Column('map_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id')
    )
    op.create_index(op.f('ix_mindmap_video_id'), 'mindmap', ['video_id'], unique=True)
    op.create_table('topic_segment',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('vid_id', sa.Integer(), nullable=True),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('main_topic', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['vid_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id'),
    sa.UniqueConstraint('vid_id', 'segment_number', name='uq_vid_segment')
    )
    op.create_table('video_studynotes',
    sa.Column('notes_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notes_id')
    )
    op.create_index(op.f('ix_video_studynotes_video_id'), 'video_studynotes', ['video_id'], unique=True)
    op.create_table('video_summary',
    sa.Column('sum_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sum_id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('current_time', sa.Integer(), nullable=True),
    sa.Column('question_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('answer_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('flashcard',
    sa.Column('flashcard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flashcard_id')
    )
    op.create_index(op.f('ix_flashcard_segment_id'), 'flashcard', ['segment_id'], unique=False)
    op.create_index(op.f('ix_flashcard_video_id'), 'flashcard', ['video_id'], unique=False)
    op.create_table('keypoints',
    sa.Column('keypoint_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keypoint_id')
    )
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('quiz_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quiz_segment_id'), 'quiz', ['segment_id'], unique=False)
    op.create_index(op.f('ix_quiz_video_id'), 'quiz', ['video_id'], unique=False)
    op.create_table('segment_studynotes',
    sa.Column('notes_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notes_id')
    )
    op.create_index(op.f('ix_segment_studynotes_segment_id'), 'segment_studynotes', ['segment_id'], unique=True)
    op.create_table('segment_summary',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('segment_id')
    )
    op.create_table('subtopics',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtopic_id')
    )
    op.create_table('quiz_question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choice_a', sa.Text(), nullable=False),
    sa.Column('choice_b', sa.Text(), nullable=False),
    sa.Column('choice_c', sa.Text(), nullable=False),
    sa.Column('choice_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('correct_answer_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('video_timestamp', sa.Integer(), nullable=True),
    sa.Column('timestamp_label', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('concept', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_quiz_question_quiz_id'), 'quiz_question', ['quiz_id'], unique=False)
    op.create_table('user_quiz_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('trials', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'user_id', name='uq_quiz_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quiz_results')
    op.drop_index(op.f('ix_quiz_question_quiz_id'), table_name='quiz_question')
    op.drop_table('quiz_question')
    op.drop_table('subtopics')
    op.drop_table('segment_summary')
    op.drop_index(op.f('ix_segment_studynotes_segment_id'), table_name='segment_studynotes')
    op.drop_table('segment_studynotes')
    op.drop_index(op.f('ix_quiz_video_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_segment_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_table('keypoints')
    op.drop_index(op.f('ix_flashcard_video_id'), table_name='flashcard')
    op.drop_index(op.f('ix_flashcard_segment_id'), table_name='flashcard')
    op.drop_table('flashcard')
    op.drop_table('chat_messages')
    op.drop_table('video_summary')
    op.drop_index(op.f('ix_video_studynotes_video_id'), table_name='video_studynotes')
    op.drop_table('video_studynotes')
    op.drop_table('topic_segment')
    op.drop_index(op.f('ix_mindmap_video_id'), table_name='mindmap')
    op.drop_table('mindmap')
    op.drop_table('content_preferences')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_video_content_hash'), table_name='video')
    op.drop_table('video')
    op.drop_table('settings')
    op.drop_table('user')
    # ### end Alembic commands ###
