"""add segments system with subtopics and keypoints

Revision ID: 9e7d38ac822f
Revises: f6caad3ea6a0
Create Date: 2026-04-13 20:46:59.787898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7d38ac822f'
down_revision: Union[str, Sequence[str], None] = 'f6caad3ea6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_segment',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('vid_id', sa.Integer(), nullable=True),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('main_topic', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vid_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id'),
    sa.UniqueConstraint('vid_id', 'segment_number', name='uq_vid_segment')
    )
    op.create_table('keypoints',
    sa.Column('keypoint_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keypoint_id')
    )
    op.create_table('subtopics',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtopic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopics')
    op.drop_table('keypoints')
    op.drop_table('topic_segment')
    # ### end Alembic commands ###
