"""add video and segment new columns

Revision ID: b371469422b3
Revises: d1e2f3a4b5c6
Create Date: 2026-05-18 05:35:29.152595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b371469422b3'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_studynotes',
    sa.Column('notes_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notes_id')
    )
    op.create_index(op.f('ix_video_studynotes_video_id'), 'video_studynotes', ['video_id'], unique=True)
    op.create_table('segment_studynotes',
    sa.Column('notes_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notes_id')
    )
    op.create_index(op.f('ix_segment_studynotes_segment_id'), 'segment_studynotes', ['segment_id'], unique=True)
    op.drop_constraint(op.f('mindmap_video_id_key'), 'mindmap', type_='unique')
    op.drop_index(op.f('ix_mindmap_video_id'), table_name='mindmap')
    op.create_index(op.f('ix_mindmap_video_id'), 'mindmap', ['video_id'], unique=True)
    op.add_column('topic_segment', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('video', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('video', sa.Column('storage_bytes', sa.BigInteger(), nullable=True))
    op.add_column('video', sa.Column('current_time', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('last_watched_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('video', sa.Column('bookmarks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'bookmarks')
    op.drop_column('video', 'last_watched_at')
    op.drop_column('video', 'current_time')
    op.drop_column('video', 'storage_bytes')
    op.drop_column('video', 'file_size')
    op.drop_column('topic_segment', 'is_completed')
    op.drop_index(op.f('ix_mindmap_video_id'), table_name='mindmap')
    op.create_index(op.f('ix_mindmap_video_id'), 'mindmap', ['video_id'], unique=False)
    op.create_unique_constraint(op.f('mindmap_video_id_key'), 'mindmap', ['video_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_segment_studynotes_segment_id'), table_name='segment_studynotes')
    op.drop_table('segment_studynotes')
    op.drop_index(op.f('ix_video_studynotes_video_id'), table_name='video_studynotes')
    op.drop_table('video_studynotes')
    # ### end Alembic commands ###
