"""init

Revision ID: bde6fcd37ca0
Revises: 
Create Date: 2026-04-29 15:51:57.117341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde6fcd37ca0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('study_field', sa.String(length=100), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('settings',
    sa.Column('sett_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sett_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('video',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vid')
    )
    op.create_index(op.f('ix_video_content_hash'), 'video', ['content_hash'], unique=False)
    op.create_table('content_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('summary_language', sa.String(length=10), nullable=True),
    sa.Column('quiz_language', sa.String(length=10), nullable=True),
    sa.Column('flashcard_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('topic_segment',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('vid_id', sa.Integer(), nullable=True),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('main_topic', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vid_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id'),
    sa.UniqueConstraint('vid_id', 'segment_number', name='uq_vid_segment')
    )
    op.create_table('video_summary',
    sa.Column('sum_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sum_id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('flashcard',
    sa.Column('flashcard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.vid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flashcard_id')
    )
    op.create_index(op.f('ix_flashcard_segment_id'), 'flashcard', ['segment_id'], unique=False)
    op.create_index(op.f('ix_flashcard_video_id'), 'flashcard', ['video_id'], unique=False)
    op.create_table('keypoints',
    sa.Column('keypoint_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keypoint_id')
    )
    op.create_table('segment_summary',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('segment_id')
    )
    op.create_table('subtopics',
    sa.Column('subtopic_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['topic_segment.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtopic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopics')
    op.drop_table('segment_summary')
    op.drop_table('keypoints')
    op.drop_index(op.f('ix_flashcard_video_id'), table_name='flashcard')
    op.drop_index(op.f('ix_flashcard_segment_id'), table_name='flashcard')
    op.drop_table('flashcard')
    op.drop_table('video_summary')
    op.drop_table('topic_segment')
    op.drop_table('content_preferences')
    op.drop_index(op.f('ix_video_content_hash'), table_name='video')
    op.drop_table('video')
    op.drop_table('settings')
    op.drop_table('user')
    # ### end Alembic commands ###
