"""add video table

Revision ID: f6caad3ea6a0
Revises: 35d278af6e63
Create Date: 2026-03-16 00:32:55.734866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6caad3ea6a0'
down_revision: Union[str, Sequence[str], None] = '35d278af6e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('upload_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vid')
    )
    op.add_column('user', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('oauth_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'is_email_verified')
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'oauth_id')
    op.drop_column('user', 'oauth_provider')
    op.drop_table('video')
    # ### end Alembic commands ###
